language: node_js
node_js:
- '12.16'
addons:
  ssh_known_hosts: 165.227.49.36
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- cd angular-src
install:
- npm install
script:
- 'true'
after_success:
- npm run build
