version: '3.7'

services:
  backend:
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file: 
      - backend_vars.env

    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    links:
      - database
  
  database:
    hostname: database
    image: mongo:latest
    env_file:
      - backend_vars.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "27017:27017"