version: '3.7'

services:
  frontend:
    hostname: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile
    volumes:
      - ./angular-src:/usr/src/app
    ports:
      - "4200:4200"