version: '3.7'

services:
  fontend:
    build: angular-src
    ports:
      - "4200:4200"
  
  backend:
    build: backend
    ports:
      - "4000:4000"
    links:
      - database
  
  database:
    image: mongo
    ports:
      - "27017:27017"