version: '3.7'

services:
  frontend:
    hostname: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile.dev
    volumes:
      - ./angular-src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
  
  backend:
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      SITE_DB_NAME: "sitedb"
      DEV_USERNAME: "devuser"
      DEV_PASSWORD: "pass"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database
  
  database:
    hostname: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "sitedb"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"