version: '3.7'

services:
  frontend:
    hostname: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile
    env_file:
      - frontend_vars.env
    ports:
      - "80:80"
      - "443:443"