version: '3.7'

services:
  frontend:
    hostname: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile
    env_file:
      - frontend_vars.env
    volumes:
      - ./angular-src:/usr/src/app
      - /usr/src/app/node_modules
      - ./angular-src/dist:/usr/src/app/dist