version: '3.7'

services:
  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile.dev
    environment:
      BACKEND_URL: "backend:4000"
    volumes:
      - ./angular-src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
  
  backend:
    hostname: backend
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      DB_NAME: "sitedb"
      DB_USERNAME: "devuser"
      DB_PASSWORD: "pass"
      DB_IP: "database:27017"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database
  
  database:
    hostname: database
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "sitedb"
      DB_USERNAME: "devuser"
      DB_PASSWORD: "pass"
      DB_NAME: "sitedb"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "27017:27017"