version: '3.7'

services:
  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile
    env_file:
      - frontend_vars.env
    volumes:
      - web-root:/usr/src/app/dist

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/html
