version: '3.7'

services:
  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: angular-src 
      dockerfile: Dockerfile
    env_file:
      - frontend_vars.env
    volumes:
      - /var/www/tmp:/usr/src/app/dist
