version: 2.1

jobs:
  test-frontend:
    working_directory: ~/personal_site/angular-src
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout:
          path: ~/personal_site
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"

workflows:
  version: 2.1
  test_workflow:
    jobs:
      - test-frontend:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test-frontend

      